builds:
  - binary: mubeng
    main: cmd/mubeng/main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
  
archives:
  - id: tgz
    format: tar.gz
    format_overrides:
        - goos: windows
          format: zip
